#!/usr/bin/env python3
"""
List skipped BATS tests on all schedules
"""

import argparse
import os
import sys

from bats.repos import REPOS, find_products, grep_tarball

GITLAB_TOKEN = os.environ.get("GITLAB_TOKEN")


def main() -> None:
    """
    Main function
    """
    parser = argparse.ArgumentParser(
        prog="bats_list",
        description="list skipped BATS tests per product",
        epilog="set GITLAB_TOKEN environment variable for gitlab",
    )
    parser.add_argument(
        "repositories",
        nargs="*",
        default=REPOS,
        metavar="repository",
        help="directory or URL",
    )
    args = parser.parse_args()

    for repo in args.repositories:
        for file in grep_tarball(repo, "*.yaml"):
            for product in find_products(file):
                print(f"{product.name}\t{product.url}")
                for setting, value in product.settings.items():
                    print(f"\t{setting}='{value}'")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
