#!/usr/bin/env python3
"""
List skipped BATS tests on all schedules
"""

import argparse
import os
import sys

from bats.repos import REPOS, SKIP, find_file, grep_dir, grep_tarball

GITLAB_TOKEN = os.environ.get("GITLAB_TOKEN")


def main() -> None:
    """
    Main function
    """
    parser = argparse.ArgumentParser(
        prog="bats_list",
        description="list skipped BATS tests per product",
        epilog="set GITLAB_TOKEN environment variable for gitlab",
    )
    parser.add_argument(
        "repositories",
        nargs="*",
        default=REPOS,
        metavar="repository",
        help="directory or URL",
    )
    args = parser.parse_args()

    for repo in args.repositories:
        if repo.startswith("https://") or not repo.startswith("/"):
            for file in grep_tarball(repo, "*.yaml"):
                for product in find_file(file):
                    print(f"{product.name}\t{product.url}")
                    for setting in sorted(filter(SKIP.search, product.settings)):
                        print(f"\t{setting}='{product.settings[setting]}'")
        else:
            for filename in grep_dir(repo, SKIP, "*.yaml", [".git"]):
                with open(filename, encoding="utf-8") as file:
                    for product in find_file(file):
                        print(f"{product.name}\t{product.url}")
                        for setting in sorted(filter(SKIP.search, product.settings)):
                            print(f"\t{setting}='{product.settings[setting]}'")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
