#!/bin/bash

IMAGE="${IMAGE:-ghcr.io/ricardobranco777/susebats:latest}"

DOCKER=$(command -v docker)
PODMAN=$(command -v podman)

# We need unprivileged user namespaces for rootless containers
if unshare -U true >/dev/null 2>&1; then
	SUDO=
else
	SUDO=${SUDO:-$(command -v sudo)}
fi

# Prefer Podman over Docker since it's daemonless and we're holy
RUNTIME="${RUNTIME:-${PODMAN:-$DOCKER}}"

opts=(
	--cap-drop=ALL
	--read-only
	--rm
	--security-opt=no-new-privileges
	--user "$(id -u):$(id -g)"
)

# Do not use sudo if we're in docker group
if [[ $RUNTIME =~ docker ]]; then
	if id -Gn | grep -qw docker; then
		SUDO=
	fi
	opts+=(--net=host)
fi

if [ "$1" = "--version" ] ; then
	latest=$(curl -s https://api.github.com/repos/ricardobranco777/susebats/tags | jq -Mr '.[0].name')
	if [ "${latest#v}" != "$($SUDO "$RUNTIME" run "${opts[@]}" "$IMAGE" --version)" ] ; then
		echo "Latest version available: $latest" >&2
	fi
fi

if [ -n "$SUDO" ]; then
	SUDO="$SUDO --preserve-env=DEBUG,BUGZILLA_TOKEN,GITHUB_TOKEN,GITLAB_TOKEN,JIRA_TOKEN,REDMINE_TOKEN,REPOS"
fi

exec $SUDO "$RUNTIME" run "${opts[@]}" -e DEBUG -e BUGZILLA_TOKEN -e GITHUB_TOKEN -e GITLAB_TOKEN -e JIRA_TOKEN -e REDMINE_TOKEN -e REPOS "$IMAGE" "$@"
