#!/bin/sh

DOCKER="${DOCKER:-podman}"
IMAGE="${IMAGE:-ghcr.io/ricardobranco777/susebats:latest}"

exec "$DOCKER" run --rm -e DEBUG -e BUGZILLA_TOKEN -e GITHUB_TOKEN -e GITLAB_TOKEN -e REDMINE_TOKEN -e REPOS "$IMAGE" "$@"
